apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
        - name: mlops-api
          image: lauradiazmondejar/mlops-api:latest
          ports:
            - containerPort: 8000
