name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  # model/
  deploy-model:
    runs-on: ubuntu-latest

    if: contains(toJson(github.event.commits.*.modified), 'model/')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install scikit-learn joblib numpy

      - name: Train model
        run: |
          python model/train.py

      - name: Upload model to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "random_forest_model.joblib"
          target: "/home/ec2-user/mlops-app/"

  # app/
  deploy-app:
    runs-on: ubuntu-latest

    if: contains(toJson(github.event.commits.*.modified), 'app/')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy API to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app/"
          target: "/home/ec2-user/mlops-app/"

      - name: Restart API on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f "python app.py" || true
            cd /home/ec2-user/mlops-app/app
            nohup python app.py > output.log 2>&1 &
